/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "color-border": "#c5cad3",
        "tertiary-container": "#d4626b",
        "color-surface": "#ffffff",
        "inverse-on-surface": "#eef2eb",
        "secondary": "#1a73b5",
        "surface-dim": "#d7dbd5",
        "color-background": "#f7f8fb",
        "on-primary-fixed-variant": "#006e3a",
        "color-debt-bg": "#dceefb",
        "on-background": "#111111",
        "surface-variant": "#e8ece6",
        "on-primary-fixed": "#00210f",
        "on-secondary": "#ffffff",
        "surface-bright": "#f6fbf4",
        "tertiary-fixed": "#ffdada",
        "on-surface-variant": "#2d3630",
        "on-surface": "#111111",
        "primary-container": "#0f9454",
        "outline": "#6f7a70",
        "surface-tint": "#009950",
        "color-expense-bg": "#fff0ee",
        "tertiary-fixed-dim": "#ffb3b6",
        "secondary-fixed-dim": "#9bccf6",
        "secondary-fixed": "#dceefb",
        "inverse-primary": "#5ee895",
        "on-error": "#ffffff",
        "color-text-primary": "#111118",
        "on-secondary-fixed-variant": "#0a5a8a",
        "color-income-bg": "#e0f7ea",
        "on-tertiary-fixed": "#40000d",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#7c2b34",
        "primary-fixed-dim": "#5ee895",
        "color-offline": "#e63832",
        "on-primary": "#ffffff",
        "color-success": "#1aad55",
        "tertiary": "#b8434d",
        "surface-container-low": "#f3f7f1",
        "on-secondary-container": "#1a6fa8",
        "background": "#f7f8fb",
        "on-primary-container": "#b2ffd0",
        "primary-fixed": "#9bf6ba",
        "on-secondary-fixed": "#001e30",
        "secondary-container": "#82c8f8",
        "on-error-container": "#c30010",
        "surface-container": "#edf1ea",
        "outline-variant": "#c8d2c8",
        "on-tertiary": "#ffffff",
        "color-debt": "#1565a0",
        "surface-container-highest": "#e0e5de",
        "surface": "#f7f8fb",
        "error-container": "#ffdad6",
        "primary": "#009950",
        "inverse-surface": "#2d322d",
        "surface-container-high": "#e8ece6",
        "error": "#d81b1b",
        "color-text-secondary": "#2D5A3D",
        "on-tertiary-container": "#ffe7e7",
        "color-warning": "#f5a623",
        "color-income": "#009950",
        "color-expense": "#e03025"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      spacing: {
        lg: "24px",
        md: "16px",
        sm: "12px",
        xl: "32px",
        xs: "8px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "section-title": ["22px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-caption": ["16px", { lineHeight: "1.2", fontWeight: "600" }],
        "button-label": ["20px", { lineHeight: "1.2", fontWeight: "700" }],
        "badge": ["14px", { lineHeight: "1.0", fontWeight: "600" }],
        "card-value": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-input": ["20px", { lineHeight: "1.7", fontWeight: "400" }],
        "clock-hero": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "page-title": ["28px", { lineHeight: "1.2", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
